### ISSUE TITLE
Issue on devices with camera resolution > viewport

### ISSUE THREAD

**Issue by athewsey** [aws-samples/liveness-detection#6]
Hi team,

From what I can tell, this solution seems to load the media stream for the web client at raw dimensions regardless of the page size. In situations where the camera has high resolution relative to the screen size (e.g. mobile browsers) this causes the page to overflow and seems to somehow break the maths of the challenge in some cases - struggling to get to green box or recognise nose placed in the yellow box.

Observed on Android devices, emulated iPhone, and laptop Firefox and Chrome (by reducing the browser window to minimum width)

**Comment by rafaelwmartins** [comment]
Hi @athewsey. The repo contains a sample web app that is not optimized for small screens. It was always meant to be a sample client without refinements necessary as a production client. I agree that that was not clear in the README. I changed the README to make that more clear.
