### ISSUE TITLE
[Feature Request] Centralized failure reason logging

### ISSUE THREAD

**Issue by athewsey** [aws-samples/liveness-detection#9]
By nature of the way the sample challenge works (split between challenge generation, on-device analytics, and Rekognition-based verification) there are multiple stages within the flow where failure can occur.

We'd like failure events (regardless of on-device vs in-cloud) to be logged in a centralized way independent of the failure reason - both for initial debugging of the app on new platforms, and for management of the challenge flows in production. For example if making changes to the generated challenges, to understand downstream impact on failure rates both for on-device and Rekognition.

**Comment by rafaelwmartins** [comment]
Hi @athewsey. Thanks for the feature request.
I agree with you that having the local logs in a central location should be useful in production environments. To do so, one could add a flush mechanism in the client to send its logs to the cloud periodically. An endpoint can be added in the API for that and Amazon CloudWatch Logs can be used to store the logs in the cloud.
Having said that, I'll not proceed with the feature request for this repo here as its purpose is to give a simple sample to start with and not a production ready system. I'll modify the README a little to clarify that and also include your suggestion there.
